// packages/react/src/DayFlowCalendar.tsx
import { CalendarRenderer } from '@dayflow/core';
import type {
  ICalendarApp,
  CustomRendering,
  UseCalendarAppReturn,
  EventContentSlotArgs,
  EventContextMenuSlotArgs,
  GridContextMenuSlotArgs,
  EventDetailContentProps,
  EventDetailDialogProps,
  CreateCalendarDialogProps,
  TitleBarSlotProps,
  ColorPickerProps,
  CreateCalendarDialogColorPickerProps,
  CalendarHeaderProps,
} from '@dayflow/core';
import { useRef, useEffect, useLayoutEffect, useState, useMemo } from 'react';

// useLayoutEffect on the client fires before paint; fall back to useEffect on
// the server to avoid SSR hydration warnings (the calendar is client-only anyway).
const useIsomorphicLayoutEffect =
  typeof window === 'undefined' ? useEffect : useLayoutEffect;
import type { ReactNode, FC } from 'react';
import { createPortal } from 'react-dom';

export interface DayFlowCalendarProps {
  calendar: ICalendarApp | UseCalendarAppReturn;
  /** Custom event content renderer for Day view timed events */
  eventContentDay?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for Week view timed events */
  eventContentWeek?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for Month view timed events */
  eventContentMonth?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for Year view events */
  eventContentYear?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Day view */
  eventContentAllDayDay?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Week view */
  eventContentAllDayWeek?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Month view */
  eventContentAllDayMonth?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Year view */
  eventContentAllDayYear?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event detail panel content (React) */
  eventDetailContent?: (args: EventDetailContentProps) => ReactNode;
  /** Custom event detail dialog (React) */
  eventDetailDialog?: (args: EventDetailDialogProps) => ReactNode;
  /** Custom create calendar dialog (React) */
  createCalendarDialog?: (args: CreateCalendarDialogProps) => ReactNode;
  /** Optional left padding to account for safe area insets (e.g. on Mac) */
  collapsedSafeAreaLeft?: number;
  /** Title bar slot (React) */
  titleBarSlot?: (context: TitleBarSlotProps) => ReactNode;
  /** Custom color picker renderer (React) */
  colorPicker?: (args: ColorPickerProps) => ReactNode;
  /** Custom create calendar dialog color picker renderer (React) */
  createCalendarDialogColorPicker?: (
    args: CreateCalendarDialogColorPickerProps
  ) => ReactNode;
  /** Custom calendar header renderer (React) */
  calendarHeader?: (args: CalendarHeaderProps) => ReactNode;
  /** Custom event right-click context menu renderer (React) */
  eventContextMenu?: (args: EventContextMenuSlotArgs) => ReactNode;
  /** Custom grid/cell right-click context menu renderer (React) */
  gridContextMenu?: (args: GridContextMenuSlotArgs) => ReactNode;
  /** Search configuration */
  search?: CalendarSearchProps;
}

/** Compute active override names from props and installed plugins. */
function computeActiveOverrides(
  app: ICalendarApp,
  renderProps: Omit<DayFlowCalendarProps, 'calendar'>
): string[] {
  const fromProps = Object.keys(renderProps).filter(
    key => (renderProps as Record<string, unknown>)[key] !== undefined
  );

  const fromPlugins: string[] = [];
  if (app?.state?.plugins) {
    app.state.plugins.forEach(plugin => {
      if (plugin.name === 'sidebar' && plugin.config) {
        const config = plugin.config as Record<string, unknown>;
        if (config['render']) {
          fromPlugins.push('sidebar');
        }
        if (config['renderCreateCalendarDialog']) {
          fromPlugins.push('createCalendarDialog');
        }
        if (config['renderCalendarContextMenu']) {
          fromPlugins.push('calendarContextMenu');
        }
        if (config['renderSidebarHeader']) {
          fromPlugins.push('sidebarHeader');
        }
      }
    });
  }

  return [...new Set([...fromProps, ...fromPlugins])];
}

/** Shallow ordered comparison — avoids JSON.stringify allocation. */
function overridesChanged(prev: string[], next: string[]): boolean {
  return prev.length !== next.length || prev.some((v, i) => v !== next[i]);
}

export const DayFlowCalendar: FC<DayFlowCalendarProps> = ({
  calendar,
  ...renderProps
}: DayFlowCalendarProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<CalendarRenderer | null>(null);
  const [customRenderings, setCustomRenderings] = useState<
    Map<string, CustomRendering>
  >(new Map());
  const [isMounted, setIsMounted] = useState(false);

  // Extract the underlying app instance
  const app =
    'app' in calendar && calendar.app
      ? calendar.app
      : (calendar as ICalendarApp);
  const renderPropsKeysRef = useRef<string[]>([]);

  useIsomorphicLayoutEffect(() => {
    setIsMounted(true);
    if (!containerRef.current || !app) {
      return;
    }

    // Compute overrides synchronously so the very first Preact render already
    // knows which slots are handled by this adapter — no race window.
    const initialOverrides = computeActiveOverrides(app, renderProps);
    renderPropsKeysRef.current = initialOverrides;

    const renderer = new CalendarRenderer(app, initialOverrides);
    rendererRef.current = renderer;
    renderer.setProps(renderProps);
    renderer.mount(containerRef.current);

    const store = renderer.getCustomRenderingStore();

    const unsubscribeStore = store.subscribe(
      (
        renderings:
          | Iterable<readonly [string, CustomRendering]>
          | null
          | undefined
      ) => {
        setCustomRenderings(new Map(renderings));
      }
    );

    return () => {
      // if React recycles this fiber on the next route.
      store.setOverrides([]);
      unsubscribeStore();
      renderer.unmount();
      rendererRef.current = null;
    };
  }, [app]);

  // Keep overrides and props in sync when they change after the initial mount.
  useEffect(() => {
    if (!rendererRef.current) {
      return;
    }
    const store = rendererRef.current.getCustomRenderingStore();

    const allOverrides = computeActiveOverrides(app, renderProps);
    if (overridesChanged(renderPropsKeysRef.current, allOverrides)) {
      store.setOverrides(allOverrides);
      app.setOverrides(allOverrides);
      renderPropsKeysRef.current = allOverrides;
    }

    rendererRef.current.setProps(renderProps);
  }, [renderProps, app]);

  // Portals for custom content
  const portals = useMemo(() => {
    if (!isMounted) {
      return [];
    }
    return [...customRenderings.values()].map((rendering: CustomRendering) => {
      const { id, containerEl, generatorName, generatorArgs } = rendering;

      // 1. Look up the generator in props
      let generator = (renderProps as Record<string, unknown>)[generatorName];

      // 2. If not in props, look up in plugins
      if (!generator && app && app.state && app.state.plugins) {
        app.state.plugins.forEach(plugin => {
          if (plugin.name === 'sidebar' && plugin.config) {
            const config = plugin.config as Record<string, unknown>;
            switch (generatorName) {
              case 'sidebar':
                generator = config['render'];
                break;
              case 'createCalendarDialog':
                generator = config['renderCreateCalendarDialog'];
                break;
              case 'calendarContextMenu':
                generator = config['renderCalendarContextMenu'];
                break;
              case 'sidebarHeader':
                generator = config['renderSidebarHeader'];
                break;
              default:
                break;
            }
          }
        });
      }

      if (!generator) {
        return null;
      }

      const content =
        typeof generator === 'function' ? generator(generatorArgs) : generator;

      return createPortal(content, containerEl, id);
    });
  }, [customRenderings, renderProps, isMounted, app]);

  return (
    <>
      <div ref={containerRef} className='df-calendar-wrapper' />
      {isMounted && portals}
    </>
  );
};

// packages/svelte/src/DayFlowCalendar.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from "svelte";
  import type { Component } from "svelte";
  import { CalendarRenderer } from "@dayflow/core";
  import type {
    ICalendarApp,
    UseCalendarAppReturn,
    CustomRendering,
    EventDetailContentProps,
    EventDetailDialogProps,
    CreateCalendarDialogProps,
    TitleBarSlotProps,
    EventContentSlotArgs,
    ColorPickerProps,
    CreateCalendarDialogColorPickerProps,
    CalendarHeaderProps,
    EventContextMenuSlotArgs,
    GridContextMenuSlotArgs,
  } from "@dayflow/core";

  const {
    calendar,
    eventContentDay = null,
    eventContentWeek = null,
    eventContentMonth = null,
    eventContentYear = null,
    eventContentAllDayDay = null,
    eventContentAllDayWeek = null,
    eventContentAllDayMonth = null,
    eventContentAllDayYear = null,
    eventDetailContent = null,
    eventDetailDialog = null,
    createCalendarDialog = null,
    titleBarSlot = null,
    colorPicker = null,
    createCalendarDialogColorPicker = null,
    calendarHeader = null,
    eventContextMenu = null,
    gridContextMenu = null,
    collapsedSafeAreaLeft = null,
  } = $props<{
    calendar: ICalendarApp | UseCalendarAppReturn;
    eventContentDay?: Component<EventContentSlotArgs>;
    eventContentWeek?: Component<EventContentSlotArgs>;
    eventContentMonth?: Component<EventContentSlotArgs>;
    eventContentYear?: Component<EventContentSlotArgs>;
    eventContentAllDayDay?: Component<EventContentSlotArgs>;
    eventContentAllDayWeek?: Component<EventContentSlotArgs>;
    eventContentAllDayMonth?: Component<EventContentSlotArgs>;
    eventContentAllDayYear?: Component<EventContentSlotArgs>;
    eventDetailContent?: Component<EventDetailContentProps>;
    eventDetailDialog?: Component<EventDetailDialogProps>;
    createCalendarDialog?: Component<CreateCalendarDialogProps>;
    titleBarSlot?: Component<TitleBarSlotProps>;
    colorPicker?: Component<ColorPickerProps>;
    createCalendarDialogColorPicker?: Component<CreateCalendarDialogColorPickerProps>;
    calendarHeader?: Component<CalendarHeaderProps>;
    eventContextMenu?: Component<EventContextMenuSlotArgs>;
    gridContextMenu?: Component<GridContextMenuSlotArgs>;
    collapsedSafeAreaLeft?: number | null;
  }>();

  let container: HTMLElement | undefined = $state();
  let renderer: CalendarRenderer | undefined;
  let customRenderings: CustomRendering[] = $state([]);
  let unsubscribe: (() => void) | undefined;
  let mounted = $state(false);

  // Guard for browser environment
  const isBrowser = typeof window !== "undefined";

  const app = $derived(
    ("app" in calendar ? calendar.app : calendar) as ICalendarApp,
  );

  const renderProps = $derived({
    eventContentDay,
    eventContentWeek,
    eventContentMonth,
    eventContentYear,
    eventContentAllDayDay,
    eventContentAllDayWeek,
    eventContentAllDayMonth,
    eventContentAllDayYear,
    eventDetailContent,
    eventDetailDialog,
    createCalendarDialog,
    titleBarSlot,
    colorPicker,
    createCalendarDialogColorPicker,
    calendarHeader,
    eventContextMenu,
    gridContextMenu,
    collapsedSafeAreaLeft,
  } as Record<string, unknown>);

  onMount(async () => {
    if (!container) {
      return;
    }

    await tick();

    const activeOverrides = Object.keys(renderProps).filter(
      (key) => renderProps[key] !== null,
    );
    renderer = new CalendarRenderer(app, activeOverrides);
    renderer.setProps(renderProps);
    renderer.mount(container);

    unsubscribe = renderer.getCustomRenderingStore().subscribe((renderings) => {
      customRenderings = [...renderings.values()];
    });

    mounted = true;
  });

  onDestroy(() => {
    if (unsubscribe) {
      unsubscribe();
    }
    if (renderer) {
      renderer.unmount();
    }
  });

  // Reactively forward prop changes to the renderer after mount.
  // `mounted` is $state so this effect re-runs when it becomes true, and
  // again whenever unknown renderProp value changes.
  $effect(() => {
    if (!mounted || !renderer) {
      return;
    }
    renderer.setProps(renderProps);
    const activeOverrides = Object.keys(renderProps).filter(
      (key) => renderProps[key] !== null,
    );
    renderer.getCustomRenderingStore().setOverrides(activeOverrides);
    app.setOverrides(activeOverrides);
  });

  function portal(node: HTMLElement, target: HTMLElement) {
    if (!target || !node || !isBrowser) {
      return;
    }
    target.append(node);
    return {
      destroy() {
        if (node.parentNode === target) {
          node.remove();
        }
      },
    };
  }
</script>

{#if isBrowser}
  <div bind:this={container} class="df-calendar-wrapper"></div>

  {#if mounted}
    {#each customRenderings as rendering (rendering.id)}
      {@const Component = renderProps[rendering.generatorName]}
      {#if Component && rendering.containerEl}
        <div use:portal={rendering.containerEl}>
          <Component {...rendering.generatorArgs} />
        </div>
      {/if}
    {/each}
  {/if}
{:else}
  <!-- SSR Placeholder -->
  <div class="df-calendar-wrapper df-calendar-ssr-placeholder"></div>
{/if}
